version: '2' #Schema version dari docker compose

services: #Mendefinisikan service yang akan digunakan
  item-app: #Layanan pertama diberi nama item-app
    image: docker.pkg.github.com/chanddr/docker-publish-dicoding/item-app:v1 #Mengganti nama image dari GitHub Packages
    ports:
      - "80:8080" #Port mapping dari port 80 host ke port 8080 container
    depends_on:
      - item-db #Item-app hanya akan berjalan setelah item-db diluncurkan
    restart: always #Restart policy agar container restart jika terhenti

  item-db: #Layanan kedua diberi nama item-db
    image: mongo:3 #Nama image yang akan digunakan untuk item-db
    volumes:
      - app-db:/data/db #Menggunakan volume bernama app-db dengan target /data/db di container
    restart: always #Restart policy agar container restart jika terhenti

volumes: #Mendefinisikan volume
  app-db: #Volume bernama app-db
